name: Deploy Node App

on:
  push:
    branches:
      - main  # or your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SSH Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull kshitija1510/nodejs-demo-app:latest
            docker stop nodejs-demo-app || true
            docker rm nodejs-demo-app || true
            docker run -d --name nodejs-demo-app -p 80:3000 kshitija1510/nodejs-demo-app:latest
